#!/bin/sh
# shellcheck disable=SC2006
MSG=$(awk '{printf("%s",$0)}' "$1")
# shellcheck disable=SC2039
if [[ "$MSG" =~ ^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([^[:space:]]{1,}\)){0,1}:' '[[:graph:]]{4,50}$ ]]; then
#  echo "\033[32m commit success! \033[0m"
  exit 0
else
  echo "\033[31m Error:提交失败！commit message 格式不符合规范  \033[m"

  echo "\033[33m 请参照以下完整的提交格式："
  cat <<EOF
type(scope of this change): Short description

Long description1
Long description2
Long description3

BREAKING CHANGE: breaking changes

Closes #issue_number
EOF
  echo "\033[0m"
  echo "\033[32m 大部分情况，只需关注首行，即正确格式为: <类型>[(影响范围)]: <主题>,其中类型只能是下面11种的其中一种,(影响范围)可选,主题4-50个字符,与冒号之间带空格 \033[0m"
  echo "\033[32m feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert \033[0m"
  exit 1
fi
